---
# How to Execute:
# ansible-playbook -i inv test-case-04.yml -v

- name: '[ToolShift][Testcase-04] Base Provision'
  hosts: all 
  become: false
  vars:
    testcase: 04
  vars_prompt:
    - name: "OS_PASSWORD"
      prompt: 'Openstack Tenant Password'
  roles:
    - { role: infra_provision, state: 'present', vm_name: 'jp-rhsso-test', os_flavor: 'ocp-lb', os_image: 'RHEL-7.4', volume_size: '20' }
    - { role: infra_provision, state: 'present', vm_name: 'cloudforms', os_flavor: 'Small', os_image: 'CFME-5.9.1', volume_size: '80' }                                                                                                                                                                                             



  #- name: '[ToolShift][Testcase-04] OCP + Insight + Tower + Self remediation'
